export { default as Main } from './Main';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Posts } from './Posts';
export { default as Profile } from './Profile';
// export { default as Category1 } from './Category1';
// export { default as Category2 } from './Category2.js';
// export { default as Category3 } from './Category3';
// export { default as PostList } from '../components/Menu/sub/PostList';
// export { default as Sidebar } from '../components/Menu/Sidebar';
